#!/bin/sh

: ${LOG:="/var/log/${PWD##*/}.log"}

export USER="syncthing"
export GROUP="$(id -Gn "$USER" | tr ' ' ':')"
export HOME="/home/${USER}"

mkdir -p "${LOG%/*}"
install -m440 -o"$USER" -g"$USER" "$LOG"

cd "${HOME}"
exec >"$LOG" 2>&1
exec chpst -u "${USER}:${GROUP}" syncthing serve --no-restart --no-browser --no-upgrade --gui-address=0.0.0.0
