#!/bin/sh
[ -r ./conf ] && . ./conf
umask 027

chmod 750 ./supervise
chmod -R 640 ./supervise/*
chown -R "$USER":"$USER" ./supervise

mkdir -p "${LOG%/*}"
install -m640 -o"$USER" -g"$USER" /dev/null "${LOG}"
ln -fs "${LOG##*/}" "${LOG%/*}/current"

[ ! -f "/etc/cron.d/minecraft-${SERVERNAME}" ] && echo "0 6 * * * root /usr/bin/sv t minecraft-${SERVERNAME}" >"/etc/cron.d/minecraft-${SERVERNAME}"

[ ! -d "${HOME}/${SERVERNAME}" ] && exit 1
cd "${HOME}/${SERVERNAME}" || exit 1
[ ! -f './run.sh' ] && exit 1

WORLDNAME="$(grep 'level-name' server.properties | cut -d= -f2)"
if [ -d "./${WORLDNAME}/datapacks/.git" ]; then
	if cd "./${WORLDNAME}/datapacks/"; then
		chpst -u "${USER}:${GROUPLIST}" sh -c 'git fetch; git reset --hard origin/main; git pull origin main'
		cd ../..
	fi
fi

chpst -u "${USER}:${GROUPLIST}" screen -S "$SERVERNAME" -X quit
chpst -u "${USER}:${GROUPLIST}" screen -wipe "$SERVERNAME"

exec chpst -u "${USER}:${GROUPLIST}" screen -DmS "$SERVERNAME" sh -c "./run.sh nogui | tee /dev/tty | tr -cd '[:alnum:]._-' >\"$LOG\""
